# Copyright 2020-2024 The MathWorks, Inc.

# Workflow to test MATLAB-Proxy while releasing to PyPi
name: Release to PyPI

on:
  release:
    types: [created]

jobs:
  call-run-unit-tests:
    # Call workflow for running node and python tests
    uses: ./.github/workflows/run-unit-tests.yml

  generate-code-coverage:
    # Generates Code coverage and uploads it
    needs: [call-run-unit-tests]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Code Coverage XML
        uses: ./.github/actions/generate-code-coverage
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}


  build_and_publish_pypi:
    needs: call-run-unit-tests
    if: success()
    # windows container is not required here
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: 
      name: release
      url: https://pypi.org/project/matlab-proxy

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.sha}}

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
  
      - name: Install Python build dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install wheel
        shell: bash
  
      - name: Build Source and Binary wheel distributions
        run: python3 setup.py bdist_wheel sdist
        shell: bash
  
      - name: Publish to PyPI.
        uses: pypa/gh-action-pypi-publish@release/v1

# pypa/gh-action-pypi-publish does not support composite action from v1.12.0 onwards.
# For more information, see : https://github.com/pypa/gh-action-pypi-publish/issues/299 