# Copyright 2023-2025 The MathWorks, Inc.

# Workflow to run MATLAB-Proxy integration tests
name: Integration testing for MATLAB Proxy

env:
  MWI_INTEG_TESTS_LOG_FILE_PATH: '${{ github.workspace }}/tests/integration/integ_test_logs.log'

on:
  # Reusable workflow
  # Trigger on workflow call
  workflow_dispatch:
  workflow_call:

jobs:
  python_tests:
    strategy:
      # fail-fast=false runs all the jobs in strategy matrix
      # irrespective of failures in a particular job, and marks
      # the entire job as failed even if one job has failed
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]
        matlab-release: [R2020b, latest]
        python-version: ['3.8', '3.11']
        node-version: ['24']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MATLAB ${{ matrix.matlab-release }}
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.matlab-release }}

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install wheel
          python3 -m pip install .[dev]

      - name: Ensure browsers are installed for playwright
        run: python3 -m playwright install --with-deps

      - name: License MATLAB Proxy
        env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        run: |
          python3 -c "from tests.integration.utils import licensing; licensing.license_matlab_proxy()"

      - name: Test with pytest
        run: python3 -m pytest tests/integration -vs

      - name: Copy Log File
        if: ${{ always() }}
        run: |
          cp ${{ github.workspace }}/tests/integration/integ_test_logs.log ${{ matrix.os }}${{ matrix.matlab-release }}${{ matrix.python-version }}.log

      - name: Make logs files available for downloading
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: MATLAB Proxy Integration Tests Log File ${{ matrix.os }}${{ matrix.matlab-release }}${{ matrix.python-version }}
          path: ${{ matrix.os }}${{ matrix.matlab-release }}${{ matrix.python-version }}.log
          retention-days: 7
