# Copyright (c) 2020-2022 The MathWorks, Inc

# Workflow that contains jobs to test MATLAB-Proxy
name: Testing MATLAB Proxy

on:
  # Reusable workflow
  # Trigger on workflow call
  workflow_call:

jobs:
  node_tests:
    strategy:
      # fail-fast=false runs all the jobs in strategy matrix
      # irrespective of failures in a particular job, and marks
      # the entire job as failed even if one job has failed
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        # build and test node project in gui directory
        working-directory: ./gui

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 13.x
        uses: actions/setup-node@v2
        with:
          node-version: 13.x

      - name: Install Node dependencies
        run: npm install

      - name: Build Project
        run: npm build --if-present

      - name: Run Node tests
        run: npm test

  python_tests:
    strategy:
      # fail-fast=false runs all the jobs in strategy matrix
      # irrespective of failures in a particular job, and marks
      # the entire job as failed even if one job has failed
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
        exclude:
        - os: windows-latest
          # Python 3.7 in Windows does not run successfully
          python-version: '3.7'
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        # Installing wheel package will slightly speed-up installing dependencies.
        # Installing the package with "[dev]" flag  will install test dependecies as well,
        # enabling us to run pytest.
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          pip install .[dev]
      - name: Lint with black
        run: black --check .

      - name: Test with pytest
        run: python -m pytest