# Copyright 2020-2025 The MathWorks, Inc.

# Workflow that contains jobs to test MATLAB Proxy
name: Testing MATLAB Proxy Integration

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  # Runs unit tests
  call-run-unit-tests:
    uses: ./.github/workflows/run-unit-tests.yml
    timeout-minutes: 15

  # Runs integration tests
  call-integration-tests:
    uses: ./.github/workflows/run-integration-tests.yml
    secrets: inherit
    timeout-minutes: 20
